export const USER_LS = "user";

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT = "LOGOUT";

export const DB_GET_USERKEYS_REQUEST = "DB_GET_USERKEYS_REQUEST";
export const DB_GET_USERKEYS_SUCCESS = "DB_GET_USERKEYS_SUCCESS";
export const DB_GET_USERKEYS_FAILURE = "DB_GET_USERKEYS_FAILURE";

export const DB_GET_PRODUCTLIST_REQUEST = "DB_GET_PRODUCTLIST_REQUEST";
export const DB_GET_PRODUCTLIST_SUCCESS = "DB_GET_PRODUCTLIST_SUCCESS";
export const DB_GET_PRODUCTLIST_FAILURE = "DB_GET_PRODUCTLIST_FAILURE";

export const DB_SET_PRODUCT_REQUEST = "DB_SET_PRODUCT_REQUEST";
export const DB_SET_PRODUCT_SUCCESS = "DB_SET_PRODUCT_SUCCESS";
export const DB_SET_PRODUCT_FAILURE = "DB_SET_PRODUCT_FAILURE";

export const DB_REMOVE_PRODUCT_SUCCESS = "DB_REMOVE_PRODUCT_SUCCESS";

